apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-file-secret-sync
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-file-secret-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-file-secret-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-file-secret-sync
subjects:
- kind: ServiceAccount
  name: go-file-secret-sync